#!/usr/bin/env bash
set -euo pipefail

# read and export dependencies
# shellcheck disable=SC1091
source /build.env

: "${GIT_SONDE:=https://github.com/projecthorus/radiosonde_auto_rx}"
PKG_NAME="sonde-decoders"
SONDE_BINARIES=(
	dft_detect
	fsk_demod
	imet4iq
	mk2a1680mod
	rs41mod
	dfm09mod
	m10mod
	m20mod
	rs92mod
	lms6Xmod
	meisei100mod
	imet54mod
	mp3h1mod
	mts01mod
	iq_dec
	weathex301d
)

if [ "${BUILD_SONDE:-}" == "y" ]; then
	log suc "Building sonde decoders..."
	export DEBIAN_FRONTEND=noninteractive
	apt-get install -y --no-install-recommends \
		build-essential \
		debhelper \
		dh-python \
		dpkg-dev \
		fakeroot \
		git \
		python3

	rm -rf radiosonde_auto_rx
	git clone "$GIT_SONDE"

	pushd radiosonde_auto_rx/auto_rx
	export PYTHONPATH=.
	pkg_version=$(python3 -m autorx.version | tr -d '\n' | tr -d '\r' | tr -d ' ')
	if [ -z "$pkg_version" ]; then
		log err "Failed to determine sonde decoder version from autorx.version"
		exit 1
	fi
	log inf "Detected radiosonde_auto_rx version ${pkg_version}"
	./build.sh
	popd

	pushd radiosonde_auto_rx
	for bin in "${SONDE_BINARIES[@]}"; do
		if [ ! -x "auto_rx/${bin}" ]; then
			log err "Missing decoder binary auto_rx/${bin}"
			exit 1
		fi
	done

	debian_dir="debian"
	rm -rf "${debian_dir}"
	mkdir -p "${debian_dir}/source"
	changelog_date=$(LC_ALL=C date -Ru)
	cat > "${debian_dir}/changelog" <<EOF
${PKG_NAME} (${pkg_version}) unstable; urgency=medium

  * Automated build from ${GIT_SONDE}

 -- OpenWebRX DEB Builder <builder@openwebrx>  ${changelog_date}
EOF
	cat > "${debian_dir}/control" <<'EOF'
Source: sonde-decoders
Section: hamradio
Priority: optional
Maintainer: OpenWebRX DEB Builder <builder@openwebrx>
Build-Depends: debhelper (>= 13)
Standards-Version: 4.6.2
Homepage: https://github.com/projecthorus/radiosonde_auto_rx
Rules-Requires-Root: no

Package: sonde-decoders
Architecture: any
Depends: ${shlibs:Depends}, ${misc:Depends}
Description: Radiosonde decoder binaries from auto_rx
 This package ships the compiled decoder executables generated by the
 radiosonde_auto_rx project, intended for use alongside OpenWebRX.
EOF
	cat > "${debian_dir}/compat" <<'EOF'
13
EOF
	cat > "${debian_dir}/source/format" <<'EOF'
3.0 (native)
EOF
	cat > "${debian_dir}/rules" <<'EOF'
#!/usr/bin/make -f
export DH_VERBOSE := 1

%:
	dh $@

override_dh_auto_configure:
	@true

override_dh_auto_build:
	@true

override_dh_auto_install:
	dh_install
EOF
	chmod +x "${debian_dir}/rules"
	{
		for bin in "${SONDE_BINARIES[@]}"; do
			printf 'auto_rx/%s usr/bin/\n' "$bin"
		done
	} > "${debian_dir}/${PKG_NAME}.install"

	dpkg-buildpackage -b -us -uc -b -j"$(nproc --ignore=4)"
	popd

	mkdir -p "${OUTPUT_DIR}"
	shopt -s nullglob
	debs=(${PKG_NAME}_*.deb)
	shopt -u nullglob
	if [ ${#debs[@]} -eq 0 ]; then
		log err "sonde decoders deb package missing"
		exit 1
	fi
	for deb in "${debs[@]}"; do
		cp "$deb" "${OUTPUT_DIR}/"
	done

	rm -f ${PKG_NAME}_*
	rm -rf radiosonde_auto_rx
fi
